# Сборка 
FROM golang:1.21-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

# Кэширование зависимостей
RUN go install github.com/percona/mongodb_exporter@v0.40.0

# Финальный образ 
FROM alpine:3.19

RUN apk add --no-cache ca-certificates && \
    rm -rf /var/cache/apk/*

COPY --from=builder /go/bin/mongodb_exporter /usr/bin/mongodb_exporter

EXPOSE 9216
ENTRYPOINT ["mongodb_exporter"]